# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiengine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagemodel',
            options={},
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='text',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='messagemodel',
            name='date',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='twitter',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
