# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-04 23:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiengine', '0002_auto_20180928_0024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='name',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='country',
            new_name='frequency',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='twitter',
            new_name='rfiltered',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='runfiltered',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='time',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='vinput',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='voutfiltered',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='voutunfiltered',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
