# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiengine', '0003_auto_20181004_2346'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=125)),
                ('password', models.TextField()),
                ('email', models.TextField()),
            ],
        ),
    ]
