# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiengine', '0004_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose_data', models.CharField(choices=[('vin', 'Input Voltage'), ('voutunfiltered', 'Unfiltered Output Voltage'), ('voutfiltered', 'Filtered Output Voltage'), ('runfiltered', 'Unfiltered Resistance'), ('rfiltered', 'Filtered Resistance')], default='vin', max_length=20)),
            ],
        ),
    ]
