# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiengine', '0005_dataform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataForm',
        ),
    ]
