# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-07 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiengine', '0006_delete_dataform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='frequency',
            new_name='pd1ir1',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='rfiltered',
            new_name='pd1ir2',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='runfiltered',
            new_name='pd1ir3',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='time',
            new_name='pd1r1',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='vinput',
            new_name='pd1r2',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='voutfiltered',
            new_name='pd1r3',
        ),
        migrations.RenameField(
            model_name='messagemodel',
            old_name='voutunfiltered',
            new_name='pd2ir1',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pd2ir2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pd2ir3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pd2r1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pd2r2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pd2r3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pd3ir1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pd3ir2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pd3ir3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pd3r1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pd3r2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='pd3r3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
