# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiengine', '0007_auto_20190507_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemodel',
            name='processedData',
            field=models.TextField(default=42),
            preserve_default=False,
        ),
    ]
