# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiengine', '0008_messagemodel_processeddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='processedData',
            new_name='StO2',
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='processedData1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='processedData2',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='messagemodel',
            name='processedData3',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
