# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiengine', '0011_auto_20190604_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='user',
            field=models.TextField(),
        ),
    ]
