# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 18:20
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiengine', '0012_auto_20190604_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='user',
            field=models.TextField(default=1, verbose_name=django.contrib.auth.models.User),
        ),
    ]
