# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiengine', '0013_auto_20190604_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemodel',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
